### ISSUE TITLE
Feature request: add a “strict” mode that throws on invalid input.

### ISSUE THREAD

**Issue by FGasper** [CindyLinz/Perl-JSON-XS-ByteString#1]
```
> perl -MJSON::XS::ByteString -e'print JSON::XS::ByteString::decode_json("n")'; echo $?
decode_json: Unconsumed characters from offset 0 at -e line 1.
0
```
It would be more helpful in many contexts for the decoder to reject invalid JSON input via an exception. Would you have any interest in extending this module to support such a mode of operation? I’d love to be able to use this module but need strict rejection of invalid input.

Thank you for your consideration!

**Comment by CindyLinz** [comment]
I'll try to add it~~

**Comment by CindyLinz** [comment]
version 1.4.0.
I add the $warn2die option on the decode_json function.

**Comment by FGasper** [comment]
Thank you!
